# Generated by Django 4.1.5 on 2024-07-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0005_paymentmodel_delete_paymentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='account_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='mobile_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
