# Generated by Django 4.1.5 on 2024-07-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0006_paymentmodel_account_no_paymentmodel_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdb',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
