# Generated by Django 4.1.5 on 2024-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0007_projectdb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='rate',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
